server:
  port: 8090

spring:
  #  mvc:
  #    view:
  #      prefix: /WEB-INF/views
  #      suffix: .jsp
  #  messages:
  #    basename: errors,messages
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jjang052
    password: 1234

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  config-location:  classpath:mapper/config/config.xml
  mapper-locations: classpath:mapper/sql/**/*.xml
  #type-aliases-package: com.jjang051.gallery.dto

file:
  path: C:/upload/
